### ISSUE TITLE
PluginConfig import fails

### ISSUE THREAD

**Issue by pfriedland** [kkthxbye-code/netbox-script-manager#7]
from extras.plugins import PluginConfig
this no longer working in Netbox 4.1.4

**Comment by kkthxbye-code** [comment]
I'll release an update soon, it's mostly done, just fixing cosmetics.

**Comment by kkthxbye-code** [comment]
@pfriedland - Please try out v1.0.0, I just pushed it. I don't work with netbox at my day job anymore, so I only did the most basic testing. Let me know how it goes.

**Comment by pfriedland** [comment]
lol, I tried to fix it. Django …

**Comment by pfriedland** [comment]
will do. I’ll test

**Comment by pfriedland** [comment]
Failed to load module customscripts.report_services:

Traceback (most recent call last):
  File "/opt/netbox/venv/lib/python3.12/site-packages/netbox_script_manager/util.py", line 76, in load_scripts
    module = importer.find_module(module_name).load_module(module_name)
             ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FileFinder' object has no attribute 'find_module'

**Comment by kkthxbye-code** [comment]
@pfriedland - That's actually because of python 3.12 removing the deprecated find_module. I'll try to fix it up, but if you are in a hurry, it should work in python 3.11.

**Comment by kkthxbye-code** [comment]
@pfriedland - Could you try v1.0.1 and see if that fixes it?

**Comment by pfriedland** [comment]
sure. thank you and will let you know.

**Comment by pfriedland** [comment]
works and looks great !! especially like the scriptArtifacts

**Comment by kkthxbye-code** [comment]
Great, I'll close this out!
